baseURL: 'https://aprd.ir/'
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'روزنوشته‌های امیرپورمند'
theme: "PaperMod"

permalinks:
# https://gohugo.io/content-management/urls/
    posts: "/:filename/"

params:
    homeInfoParams:
        Title: سلام امیر پورمند هستم
        Content: اینجا برای دل خودم می‌نویسم

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/pourmand1376"
        - name: "twitter"
          url: "https://twitter.com/pourmand_amir"
     

languages:
    fa:
        languageName: "farsi"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series