baseURL: https://papermod-farsi.netlify.app
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'وبلاگ آزاد'
theme: "PaperMod"
paginate: 5
copyright: نوشته‌های این وبلاگ با پروانه [کریتیو کامنز اتریبیوشن ۴.۰ اینترنشنال](https://creativecommons.org/licenses/by/4.0/)  منتشر شده‌اند.

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

publishDir: "public"

googleAnalytics: UA-123-45
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: وبلاگ آزاد
  description: "وبلاگ آزاد"
  keywords: ["blog", "experience", "personal blog", "mohammad mahdi aslani"]
  author: "محمد مهدی"
  # author: ["Me", "You"] # multiple authors
  images: [""]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: ""
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: ""

  label:
    text: "وبلاگ آزاد"
    icon: #/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: سلام محمد مهدی اصلانی هستم
    Content: >
        این یک وبلاگ شخصی از منه و من سعی میکنم کارهایی که انجام میدم و چیزایی که بلدم و کاربردی هستن رو در این وبلاگ قرار بدم

  socialIcons:
    - name: rss
      url: https://aprd.ir/index.xml
    # - name: twitter
    #   url: "https://twitter.com/pourmand_amir"
    #- name: github
    #  url: "https://github.com/pourmand1376"
    - name: telegram
      url: "https://t.me/khode_mohammadmahdi"
    - name: site
      url: https://amirpourmand.ir

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Mohammad-Mahdi-Aslani/hugo-papermod-farsi-template/tree/master/content"
    Text: "پیشنهاد برای ویرایش پست" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

permalinks:
# https://gohugo.io/content-management/urls/
    posts: "/:filename/"
    

menu:
  main:
    - identifier: FATags
      name: تگ‌ها
      url: /fatags/
      weight: 20
    - identifier: archives
      name: آرشیو
      url: /archives/
      weight: 30
    - identifier: search
      name: جستجو
      url: /search/
      weight: 40

languages:
    fa:
        languageName: "farsi"
        weight: 1
        languagedirection: rtl
        taxonomies:
          category: categories
          tag: fatags
          series: series
