baseURL: 'http://aprd.ir/'
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'روزنوشته‌های امیرپورمند'
theme: "PaperMod"

permalinks:
    blog: "/:title/"

params:
    homeInfoParams:
        Title: سلام امیر پورمند هستم
        Content: اینجا برای دل خودم می‌نویسم

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/pourmand1376"
        - name: "twitter"
          url: "https://twitter.com/pourmand_amir"
    
    customcss:  
        - "/static/css/custom.css"
    #customjscssraw:
        #- <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />
        

languages:
    fa:
        languageName: "farsi"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series